services:
  postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_DB=spring_boot_advanced
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5433:5432
    restart: always
#    labels:
#      org.springframework.boot.service-connection: redis