#calculator:
#  lhs: 11
#  rhs: 99
#  op: "*"
logging:
  file:
    path: /var/log
    name: application.log
  level:
    org:
      springframework:
        web: debug
server:
  port: 8080
  error:
    whitelabel:
      enabled: true
    include-stacktrace: never