#calculator:
#  lhs: 11
#  rhs: 99
#  op: "*"
logging:
  file:
    path: /var/log
    name: application.log
  level:
    org:
      springframework:
        web: debug
server:
  port: 8080
  error:
    whitelabel:
      enabled: true
    include-stacktrace: never
  ssl:
    key-store: classpath:korsakov.pfx
    key-store-type: pkcs12
    key-store-password: password
    key-password: password
    key-alias: korsakov
    enabled: true
spring:
  messages:
    fallback-to-system-locale: false